name: Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'event-manager frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd "event-manager frontend"
        npm ci
        
    - name: Run linter
      run: |
        cd "event-manager frontend"
        npm run lint
        
    - name: Build application
      run: |
        cd "event-manager frontend"
        npm run build
        
    - name: Test build output
      run: |
        cd "event-manager frontend"
        ls -la dist/
        echo "Build completed successfully!"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: event-manager frontend/dist/
        retention-days: 30
